/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#define BOARD_INITDEBUG_UART_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x01U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */
#define BOARD_INITDEBUG_UART_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x07010000U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_AD_B0_10 (coord G13), SWO */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_INT1_COMBO_PERIPHERAL                           ARM   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_INT1_COMBO_SIGNAL                     arm_trace_swo   /*!< Signal name */

/* GPIO_AD_B0_13 (coord L14), UART1_RX */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_ASYNC_CTRL_DPU_RX_PERIPHERAL                LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_ASYNC_CTRL_DPU_RX_SIGNAL                         RX   /*!< Signal name */

/* GPIO_AD_B0_12 (coord K14), UART1_TX */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_ASYNC_CTRL_DPU_TX_PERIPHERAL                LPUART1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_ASYNC_CTRL_DPU_TX_SIGNAL                         TX   /*!< Signal name */

/* GPIO_AD_B0_00 (coord M14), ESP_EN */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_ESP_EN_PERIPHERAL                             GPIO1   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_ESP_EN_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITDEBUG_UART_ESP_EN_CHANNEL                                   0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UART_ESP_EN_GPIO                                   GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UART_ESP_EN_GPIO_PIN                                  0U   /*!< GPIO pin number */
#define BOARD_INITDEBUG_UART_ESP_EN_GPIO_PIN_MASK                     (1U << 0U)   /*!< GPIO pin mask */
#define BOARD_INITDEBUG_UART_ESP_EN_PORT                                   GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITDEBUG_UART_ESP_EN_PIN                                       0U   /*!< PORT pin number */
#define BOARD_INITDEBUG_UART_ESP_EN_PIN_MASK                          (1U << 0U)   /*!< PORT pin mask */

/* GPIO_B1_09 (coord A13), DEBUG2 */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_DEBUG2_PERIPHERAL                             GPIO7   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_DEBUG2_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITDEBUG_UART_DEBUG2_CHANNEL                                  25U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UART_DEBUG2_GPIO                                   GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UART_DEBUG2_GPIO_PIN                                 25U   /*!< GPIO pin number */
#define BOARD_INITDEBUG_UART_DEBUG2_GPIO_PIN_MASK                    (1U << 25U)   /*!< GPIO pin mask */
#define BOARD_INITDEBUG_UART_DEBUG2_PORT                                   GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INITDEBUG_UART_DEBUG2_PIN                                      25U   /*!< PORT pin number */
#define BOARD_INITDEBUG_UART_DEBUG2_PIN_MASK                         (1U << 25U)   /*!< PORT pin mask */

/* GPIO_B1_10 (coord B13), DEBUG3 */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_DEBUG3_PERIPHERAL                             GPIO7   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_DEBUG3_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITDEBUG_UART_DEBUG3_CHANNEL                                  26U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UART_DEBUG3_GPIO                                   GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UART_DEBUG3_GPIO_PIN                                 26U   /*!< GPIO pin number */
#define BOARD_INITDEBUG_UART_DEBUG3_GPIO_PIN_MASK                    (1U << 26U)   /*!< GPIO pin mask */
#define BOARD_INITDEBUG_UART_DEBUG3_PORT                                   GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INITDEBUG_UART_DEBUG3_PIN                                      26U   /*!< PORT pin number */
#define BOARD_INITDEBUG_UART_DEBUG3_PIN_MASK                         (1U << 26U)   /*!< PORT pin mask */

/* GPIO_B1_08 (coord A12), DEBUG1 */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_DEBUG1_PERIPHERAL                             GPIO7   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_DEBUG1_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITDEBUG_UART_DEBUG1_CHANNEL                                  24U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UART_DEBUG1_GPIO                                   GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UART_DEBUG1_GPIO_PIN                                 24U   /*!< GPIO pin number */
#define BOARD_INITDEBUG_UART_DEBUG1_GPIO_PIN_MASK                    (1U << 24U)   /*!< GPIO pin mask */
#define BOARD_INITDEBUG_UART_DEBUG1_PORT                                   GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INITDEBUG_UART_DEBUG1_PIN                                      24U   /*!< PORT pin number */
#define BOARD_INITDEBUG_UART_DEBUG1_PIN_MASK                         (1U << 24U)   /*!< PORT pin mask */

/* GPIO_B1_00 (coord A11), DEBUG0 */
/* Routed pin properties */
#define BOARD_INITDEBUG_UART_DEBUG0_PERIPHERAL                             GPIO7   /*!< Peripheral name */
#define BOARD_INITDEBUG_UART_DEBUG0_SIGNAL                               gpio_io   /*!< Signal name */
#define BOARD_INITDEBUG_UART_DEBUG0_CHANNEL                                  16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITDEBUG_UART_DEBUG0_GPIO                                   GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITDEBUG_UART_DEBUG0_GPIO_PIN                                 16U   /*!< GPIO pin number */
#define BOARD_INITDEBUG_UART_DEBUG0_GPIO_PIN_MASK                    (1U << 16U)   /*!< GPIO pin mask */
#define BOARD_INITDEBUG_UART_DEBUG0_PORT                                   GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INITDEBUG_UART_DEBUG0_PIN                                      16U   /*!< PORT pin number */
#define BOARD_INITDEBUG_UART_DEBUG0_PIN_MASK                         (1U << 16U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UART(void);

/* GPIO_SD_B1_07 (coord L4), FlexSPI_CLK */
/* Routed pin properties */
#define QSPI_FLASH_FlexSPI_CLK_PERIPHERAL                                FLEXSPI   /*!< Peripheral name */
#define QSPI_FLASH_FlexSPI_CLK_SIGNAL                             FLEXSPI_A_SCLK   /*!< Signal name */

/* GPIO_SD_B1_10 (coord P4), FlexSPI_D2_A */
/* Routed pin properties */
#define QSPI_FLASH_FlexSPI_D2_A_PERIPHERAL                               FLEXSPI   /*!< Peripheral name */
#define QSPI_FLASH_FlexSPI_D2_A_SIGNAL                           FLEXSPI_A_DATA2   /*!< Signal name */

/* GPIO_SD_B1_08 (coord P3), FlexSPI_D0_A */
/* Routed pin properties */
#define QSPI_FLASH_FlexSPI_D0_A_PERIPHERAL                               FLEXSPI   /*!< Peripheral name */
#define QSPI_FLASH_FlexSPI_D0_A_SIGNAL                           FLEXSPI_A_DATA0   /*!< Signal name */

/* GPIO_SD_B1_09 (coord N4), FlexSPI_D1_A */
/* Routed pin properties */
#define QSPI_FLASH_FlexSPI_D1_A_PERIPHERAL                               FLEXSPI   /*!< Peripheral name */
#define QSPI_FLASH_FlexSPI_D1_A_SIGNAL                           FLEXSPI_A_DATA1   /*!< Signal name */

/* GPIO_SD_B1_06 (coord L3), FlexSPI_SS0 */
/* Routed pin properties */
#define QSPI_FLASH_FlexSPI_SS0_PERIPHERAL                                FLEXSPI   /*!< Peripheral name */
#define QSPI_FLASH_FlexSPI_SS0_SIGNAL                            FLEXSPI_A_SS0_B   /*!< Signal name */

/* GPIO_SD_B1_11 (coord P5), FlexSPI_D3_A */
/* Routed pin properties */
#define QSPI_FLASH_FlexSPI_D3_A_PERIPHERAL                               FLEXSPI   /*!< Peripheral name */
#define QSPI_FLASH_FlexSPI_D3_A_SIGNAL                           FLEXSPI_A_DATA3   /*!< Signal name */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void QSPI_Flash(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void RAM(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Boot_Config(void);

#define EXTERNAL_CONNECTIONS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0xE0000000U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */
#define EXTERNAL_CONNECTIONS_IOMUXC_GPR_GPR28_GPIO_MUX3_GPIO_SEL_MASK 0x010000U /*!< GPIO3 and GPIO8 share same IO MUX function, GPIO_MUX3 selects one GPIO function: affected bits mask */
#define EXTERNAL_CONNECTIONS_IOMUXC_GPR_GPR29_GPIO_MUX4_GPIO_SEL_MASK 0x40U /*!< GPIO4 and GPIO9 share same IO MUX function, GPIO_MUX4 selects one GPIO function: affected bits mask */

/* GPIO_AD_B1_01 (coord K11), I2C1_SDA */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_EXT_SDA_PERIPHERAL                           LPI2C1   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_EXT_SDA_SIGNAL                                  SDA   /*!< Signal name */

/* GPIO_AD_B1_00 (coord J11), I2C1_SCL */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_EXT_SCL_PERIPHERAL                           LPI2C1   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_EXT_SCL_SIGNAL                                  SCL   /*!< Signal name */

/* GPIO_SD_B0_00 (coord J4), I2C3_SDA */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_ESP_SDA_PERIPHERAL                           LPI2C3   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_ESP_SDA_SIGNAL                                  SCL   /*!< Signal name */

/* GPIO_SD_B0_01 (coord J3), I2C3_SCL */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_ESP_SCL_PERIPHERAL                           LPI2C3   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_ESP_SCL_SIGNAL                                  SDA   /*!< Signal name */

/* GPIO_AD_B1_15 (coord J14), SPI3_SCK */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_ADC_SCK_PERIPHERAL                           LPSPI3   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_ADC_SCK_SIGNAL                                  SCK   /*!< Signal name */

/* GPIO_AD_B1_13 (coord H11), SPI3_MISO */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_ADC_MISO_PERIPHERAL                          LPSPI3   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_ADC_MISO_SIGNAL                                 SDI   /*!< Signal name */

/* GPIO_AD_B1_14 (coord G12), SPI3_MOSI */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_ADC_MOSI_PERIPHERAL                          LPSPI3   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_ADC_MOSI_SIGNAL                                 SDO   /*!< Signal name */

/* GPIO_AD_B1_12 (coord H12), SPI3_CS */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_ADC_CS_PERIPHERAL                            LPSPI3   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_ADC_CS_SIGNAL                                  PCS0   /*!< Signal name */

/* GPIO_EMC_07 (coord H4), FLEX_SDA */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_BAT_SDA_PERIPHERAL                          FLEXIO1   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_BAT_SDA_SIGNAL                                   IO   /*!< Signal name */
#define EXTERNAL_CONNECTIONS_BAT_SDA_CHANNEL                                  7U   /*!< Signal channel */

/* GPIO_EMC_08 (coord H3), FLEX_SCL */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_BAT_SCL_PERIPHERAL                          FLEXIO1   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_BAT_SCL_SIGNAL                                   IO   /*!< Signal name */
#define EXTERNAL_CONNECTIONS_BAT_SCL_CHANNEL                                  8U   /*!< Signal channel */

/* GPIO_B1_04 (coord E12), SPI4_CS */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_IMU_CS_PERIPHERAL                            LPSPI4   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_IMU_CS_SIGNAL                                  PCS0   /*!< Signal name */

/* GPIO_B1_07 (coord B12), SPI4_CLK */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_IMU_CLK_PERIPHERAL                           LPSPI4   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_IMU_CLK_SIGNAL                                  SCK   /*!< Signal name */

/* GPIO_B1_05 (coord D12), SPI4_MISO */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_IMU_MISO_PERIPHERAL                          LPSPI4   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_IMU_MISO_SIGNAL                                 SDI   /*!< Signal name */

/* GPIO_B1_06 (coord C12), SPI4_MOSI */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_IMU_MOSI_PERIPHERAL                          LPSPI4   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_IMU_MOSI_SIGNAL                                 SDO   /*!< Signal name */

/* GPIO_B1_15 (coord B14), IMU_SYNC */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_IMU_SYNC_PERIPHERAL                           GPIO7   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_IMU_SYNC_SIGNAL                             gpio_io   /*!< Signal name */
#define EXTERNAL_CONNECTIONS_IMU_SYNC_CHANNEL                                31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define EXTERNAL_CONNECTIONS_IMU_SYNC_GPIO                                 GPIO7   /*!< GPIO peripheral base pointer */
#define EXTERNAL_CONNECTIONS_IMU_SYNC_GPIO_PIN                               31U   /*!< GPIO pin number */
#define EXTERNAL_CONNECTIONS_IMU_SYNC_GPIO_PIN_MASK                  (1U << 31U)   /*!< GPIO pin mask */
#define EXTERNAL_CONNECTIONS_IMU_SYNC_PORT                                 GPIO7   /*!< PORT peripheral base pointer */
#define EXTERNAL_CONNECTIONS_IMU_SYNC_PIN                                    31U   /*!< PORT pin number */
#define EXTERNAL_CONNECTIONS_IMU_SYNC_PIN_MASK                       (1U << 31U)   /*!< PORT pin mask */

/* GPIO_B1_14 (coord C14), IMU_INT1 */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_IMU_INT1_PERIPHERAL                           GPIO7   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_IMU_INT1_SIGNAL                             gpio_io   /*!< Signal name */
#define EXTERNAL_CONNECTIONS_IMU_INT1_CHANNEL                                30U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define EXTERNAL_CONNECTIONS_IMU_INT1_GPIO                                 GPIO7   /*!< GPIO peripheral base pointer */
#define EXTERNAL_CONNECTIONS_IMU_INT1_GPIO_PIN                               30U   /*!< GPIO pin number */
#define EXTERNAL_CONNECTIONS_IMU_INT1_GPIO_PIN_MASK                  (1U << 30U)   /*!< GPIO pin mask */
#define EXTERNAL_CONNECTIONS_IMU_INT1_PORT                                 GPIO7   /*!< PORT peripheral base pointer */
#define EXTERNAL_CONNECTIONS_IMU_INT1_PIN                                    30U   /*!< PORT pin number */
#define EXTERNAL_CONNECTIONS_IMU_INT1_PIN_MASK                       (1U << 30U)   /*!< PORT pin mask */

/* GPIO_B1_13 (coord D14), IMU_INT2 */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_IMU_INT2_PERIPHERAL                           GPIO7   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_IMU_INT2_SIGNAL                             gpio_io   /*!< Signal name */
#define EXTERNAL_CONNECTIONS_IMU_INT2_CHANNEL                                29U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define EXTERNAL_CONNECTIONS_IMU_INT2_GPIO                                 GPIO7   /*!< GPIO peripheral base pointer */
#define EXTERNAL_CONNECTIONS_IMU_INT2_GPIO_PIN                               29U   /*!< GPIO pin number */
#define EXTERNAL_CONNECTIONS_IMU_INT2_GPIO_PIN_MASK                  (1U << 29U)   /*!< GPIO pin mask */
#define EXTERNAL_CONNECTIONS_IMU_INT2_PORT                                 GPIO7   /*!< PORT peripheral base pointer */
#define EXTERNAL_CONNECTIONS_IMU_INT2_PIN                                    29U   /*!< PORT pin number */
#define EXTERNAL_CONNECTIONS_IMU_INT2_PIN_MASK                       (1U << 29U)   /*!< PORT pin mask */

/* GPIO_EMC_06 (coord H5), BATMANG_INT */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_BATMANG_INT_PERIPHERAL                        GPIO9   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_BATMANG_INT_SIGNAL                          gpio_io   /*!< Signal name */
#define EXTERNAL_CONNECTIONS_BATMANG_INT_CHANNEL                              6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define EXTERNAL_CONNECTIONS_BATMANG_INT_GPIO                              GPIO9   /*!< GPIO peripheral base pointer */
#define EXTERNAL_CONNECTIONS_BATMANG_INT_GPIO_PIN                             6U   /*!< GPIO pin number */
#define EXTERNAL_CONNECTIONS_BATMANG_INT_GPIO_PIN_MASK                (1U << 6U)   /*!< GPIO pin mask */
#define EXTERNAL_CONNECTIONS_BATMANG_INT_PORT                              GPIO9   /*!< PORT peripheral base pointer */
#define EXTERNAL_CONNECTIONS_BATMANG_INT_PIN                                  6U   /*!< PORT pin number */
#define EXTERNAL_CONNECTIONS_BATMANG_INT_PIN_MASK                     (1U << 6U)   /*!< PORT pin mask */

/* GPIO_SD_B0_03 (coord K1), RGB_B */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_RGB_B_PERIPHERAL                               PWM1   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_RGB_B_SIGNAL                                      B   /*!< Signal name */
#define EXTERNAL_CONNECTIONS_RGB_B_CHANNEL                                    1U   /*!< Signal channel */

/* GPIO_SD_B0_02 (coord J1), RGB_G */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_RGB_G_PERIPHERAL                               PWM1   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_RGB_G_SIGNAL                                      A   /*!< Signal name */
#define EXTERNAL_CONNECTIONS_RGB_G_CHANNEL                                    1U   /*!< Signal channel */

/* GPIO_SD_B0_05 (coord J2), RGB_R */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_RGB_R_PERIPHERAL                               PWM1   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_RGB_R_SIGNAL                                      B   /*!< Signal name */
#define EXTERNAL_CONNECTIONS_RGB_R_CHANNEL                                    2U   /*!< Signal channel */

/* GPIO_SD_B0_04 (coord H2), V_MYOMOD_EN */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_V_MYOMOD_EN_PERIPHERAL                        GPIO8   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_V_MYOMOD_EN_SIGNAL                          gpio_io   /*!< Signal name */
#define EXTERNAL_CONNECTIONS_V_MYOMOD_EN_CHANNEL                             16U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define EXTERNAL_CONNECTIONS_V_MYOMOD_EN_GPIO                              GPIO8   /*!< GPIO peripheral base pointer */
#define EXTERNAL_CONNECTIONS_V_MYOMOD_EN_GPIO_PIN                            16U   /*!< GPIO pin number */
#define EXTERNAL_CONNECTIONS_V_MYOMOD_EN_GPIO_PIN_MASK               (1U << 16U)   /*!< GPIO pin mask */
#define EXTERNAL_CONNECTIONS_V_MYOMOD_EN_PORT                              GPIO8   /*!< PORT peripheral base pointer */
#define EXTERNAL_CONNECTIONS_V_MYOMOD_EN_PIN                                 16U   /*!< PORT pin number */
#define EXTERNAL_CONNECTIONS_V_MYOMOD_EN_PIN_MASK                    (1U << 16U)   /*!< PORT pin mask */

/* GPIO_AD_B0_14 (coord H14), ADC_RDY */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_ADC_RDY_PERIPHERAL                           LPSPI3   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_ADC_RDY_SIGNAL                                  TRG   /*!< Signal name */

/* GPIO_AD_B1_09 (coord M13), V_BAT */
/* Routed pin properties */
#define EXTERNAL_CONNECTIONS_V_BAT_PERIPHERAL                               ADC1   /*!< Peripheral name */
#define EXTERNAL_CONNECTIONS_V_BAT_SIGNAL                                     IN   /*!< Signal name */
#define EXTERNAL_CONNECTIONS_V_BAT_CHANNEL                                   14U   /*!< Signal channel */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void External_Connections(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
