/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * Copyright 2018-2025 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __RTE_DEVICE_H
#define __RTE_DEVICE_H

/***********************************************************************************************************************
 * Driver name mapping
 **********************************************************************************************************************/
/* Enable peripheral */
#define RTE_USART1 1
/* Enable peripheral */
#define RTE_SPI3 1

/***********************************************************************************************************************
 * Driver configuration
 **********************************************************************************************************************/
/* All USART Rx buffers length */
#define USART_RX_BUFFER_LEN 64
/* Enable RX buffer */
#define USART1_RX_BUFFER_ENABLE 1
/* PCS to SCK delay. */
#define RTE_SPI3_PCS_TO_SCK_DELAY 0
/* SCK to PCS delay. */
#define RTE_SPI3_SCK_TO_PSC_DELAY 0
/* Between transfer delay. */
#define RTE_SPI3_BETWEEN_TRANSFER_DELAY 0
/* Peripheral chip select. */
#define RTE_SPI3_MASTER_PCS_PIN_SEL kLPSPI_MasterPcs0


#endif /* __RTE_DEVICE_H */
